FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o datanode ./cmd/datanode

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/datanode .
EXPOSE 50052
CMD ["./datanode"]