// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/datanode.proto

package datanode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataNode_StoreChunk_FullMethodName = "/datanode.DataNode/StoreChunk"
	DataNode_FetchChunk_FullMethodName = "/datanode.DataNode/FetchChunk"
)

// DataNodeClient is the client API for DataNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataNodeClient interface {
	StoreChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StoreChunkRequest, StoreChunkResponse], error)
	FetchChunk(ctx context.Context, in *RetrieveChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RetrieveChunkResponse], error)
}

type dataNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewDataNodeClient(cc grpc.ClientConnInterface) DataNodeClient {
	return &dataNodeClient{cc}
}

func (c *dataNodeClient) StoreChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StoreChunkRequest, StoreChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataNode_ServiceDesc.Streams[0], DataNode_StoreChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StoreChunkRequest, StoreChunkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataNode_StoreChunkClient = grpc.ClientStreamingClient[StoreChunkRequest, StoreChunkResponse]

func (c *dataNodeClient) FetchChunk(ctx context.Context, in *RetrieveChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RetrieveChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataNode_ServiceDesc.Streams[1], DataNode_FetchChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RetrieveChunkRequest, RetrieveChunkResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataNode_FetchChunkClient = grpc.ServerStreamingClient[RetrieveChunkResponse]

// DataNodeServer is the server API for DataNode service.
// All implementations must embed UnimplementedDataNodeServer
// for forward compatibility.
type DataNodeServer interface {
	StoreChunk(grpc.ClientStreamingServer[StoreChunkRequest, StoreChunkResponse]) error
	FetchChunk(*RetrieveChunkRequest, grpc.ServerStreamingServer[RetrieveChunkResponse]) error
	mustEmbedUnimplementedDataNodeServer()
}

// UnimplementedDataNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataNodeServer struct{}

func (UnimplementedDataNodeServer) StoreChunk(grpc.ClientStreamingServer[StoreChunkRequest, StoreChunkResponse]) error {
	return status.Error(codes.Unimplemented, "method StoreChunk not implemented")
}
func (UnimplementedDataNodeServer) FetchChunk(*RetrieveChunkRequest, grpc.ServerStreamingServer[RetrieveChunkResponse]) error {
	return status.Error(codes.Unimplemented, "method FetchChunk not implemented")
}
func (UnimplementedDataNodeServer) mustEmbedUnimplementedDataNodeServer() {}
func (UnimplementedDataNodeServer) testEmbeddedByValue()                  {}

// UnsafeDataNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataNodeServer will
// result in compilation errors.
type UnsafeDataNodeServer interface {
	mustEmbedUnimplementedDataNodeServer()
}

func RegisterDataNodeServer(s grpc.ServiceRegistrar, srv DataNodeServer) {
	// If the following call panics, it indicates UnimplementedDataNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataNode_ServiceDesc, srv)
}

func _DataNode_StoreChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataNodeServer).StoreChunk(&grpc.GenericServerStream[StoreChunkRequest, StoreChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataNode_StoreChunkServer = grpc.ClientStreamingServer[StoreChunkRequest, StoreChunkResponse]

func _DataNode_FetchChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RetrieveChunkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataNodeServer).FetchChunk(m, &grpc.GenericServerStream[RetrieveChunkRequest, RetrieveChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataNode_FetchChunkServer = grpc.ServerStreamingServer[RetrieveChunkResponse]

// DataNode_ServiceDesc is the grpc.ServiceDesc for DataNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datanode.DataNode",
	HandlerType: (*DataNodeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StoreChunk",
			Handler:       _DataNode_StoreChunk_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FetchChunk",
			Handler:       _DataNode_FetchChunk_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/datanode.proto",
}
