// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/namenode.proto

package namenode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNodeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ip             string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port           int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	AvailableSpace int64                  `protobuf:"varint,3,opt,name=available_space,json=availableSpace,proto3" json:"available_space,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_proto_namenode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RegisterNodeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterNodeRequest) GetAvailableSpace() int64 {
	if x != nil {
		return x.AvailableSpace
	}
	return 0
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_proto_namenode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AvailableSpace int64                  `protobuf:"varint,2,opt,name=available_space,json=availableSpace,proto3" json:"available_space,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_namenode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetAvailableSpace() int64 {
	if x != nil {
		return x.AvailableSpace
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_namenode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type AllocateChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ChunkIds      []string               `protobuf:"bytes,2,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateChunksRequest) Reset() {
	*x = AllocateChunksRequest{}
	mi := &file_proto_namenode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunksRequest) ProtoMessage() {}

func (x *AllocateChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunksRequest.ProtoReflect.Descriptor instead.
func (*AllocateChunksRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{4}
}

func (x *AllocateChunksRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AllocateChunksRequest) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

type NodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds       []string               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	mi := &file_proto_namenode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{5}
}

func (x *NodeList) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type AllocateChunksResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChunkLocations map[string]*NodeList   `protobuf:"bytes,1,rep,name=chunk_locations,json=chunkLocations,proto3" json:"chunk_locations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AllocateChunksResponse) Reset() {
	*x = AllocateChunksResponse{}
	mi := &file_proto_namenode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateChunksResponse) ProtoMessage() {}

func (x *AllocateChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateChunksResponse.ProtoReflect.Descriptor instead.
func (*AllocateChunksResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{6}
}

func (x *AllocateChunksResponse) GetChunkLocations() map[string]*NodeList {
	if x != nil {
		return x.ChunkLocations
	}
	return nil
}

type ConfirmChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmChunkRequest) Reset() {
	*x = ConfirmChunkRequest{}
	mi := &file_proto_namenode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmChunkRequest) ProtoMessage() {}

func (x *ConfirmChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmChunkRequest.ProtoReflect.Descriptor instead.
func (*ConfirmChunkRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{7}
}

func (x *ConfirmChunkRequest) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ConfirmChunkRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ConfirmChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmChunkResponse) Reset() {
	*x = ConfirmChunkResponse{}
	mi := &file_proto_namenode_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmChunkResponse) ProtoMessage() {}

func (x *ConfirmChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmChunkResponse.ProtoReflect.Descriptor instead.
func (*ConfirmChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetFileLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileLocationRequest) Reset() {
	*x = GetFileLocationRequest{}
	mi := &file_proto_namenode_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileLocationRequest) ProtoMessage() {}

func (x *GetFileLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileLocationRequest.ProtoReflect.Descriptor instead.
func (*GetFileLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{9}
}

func (x *GetFileLocationRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type GetFileLocationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChunkLocations map[string]*NodeList   `protobuf:"bytes,1,rep,name=chunk_locations,json=chunkLocations,proto3" json:"chunk_locations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFileLocationResponse) Reset() {
	*x = GetFileLocationResponse{}
	mi := &file_proto_namenode_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileLocationResponse) ProtoMessage() {}

func (x *GetFileLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_namenode_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileLocationResponse.ProtoReflect.Descriptor instead.
func (*GetFileLocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_namenode_proto_rawDescGZIP(), []int{10}
}

func (x *GetFileLocationResponse) GetChunkLocations() map[string]*NodeList {
	if x != nil {
		return x.ChunkLocations
	}
	return nil
}

var File_proto_namenode_proto protoreflect.FileDescriptor

const file_proto_namenode_proto_rawDesc = "" +
	"\n" +
	"\x14proto/namenode.proto\x12\bnamenode\"b\n" +
	"\x13RegisterNodeRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12'\n" +
	"\x0favailable_space\x18\x03 \x01(\x03R\x0eavailableSpace\"I\n" +
	"\x14RegisterNodeResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"T\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12'\n" +
	"\x0favailable_space\x18\x02 \x01(\x03R\x0eavailableSpace\")\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\"Q\n" +
	"\x15AllocateChunksRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tchunk_ids\x18\x02 \x03(\tR\bchunkIds\"%\n" +
	"\bNodeList\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\"\xce\x01\n" +
	"\x16AllocateChunksResponse\x12]\n" +
	"\x0fchunk_locations\x18\x01 \x03(\v24.namenode.AllocateChunksResponse.ChunkLocationsEntryR\x0echunkLocations\x1aU\n" +
	"\x13ChunkLocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.namenode.NodeListR\x05value:\x028\x01\"I\n" +
	"\x13ConfirmChunkRequest\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"0\n" +
	"\x14ConfirmChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x16GetFileLocationRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\"\xd0\x01\n" +
	"\x17GetFileLocationResponse\x12^\n" +
	"\x0fchunk_locations\x18\x01 \x03(\v25.namenode.GetFileLocationResponse.ChunkLocationsEntryR\x0echunkLocations\x1aU\n" +
	"\x13ChunkLocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.namenode.NodeListR\x05value:\x028\x012\x9b\x03\n" +
	"\bNameNode\x12M\n" +
	"\fRegisterNode\x12\x1d.namenode.RegisterNodeRequest\x1a\x1e.namenode.RegisterNodeResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.namenode.HeartbeatRequest\x1a\x1b.namenode.HeartbeatResponse\x12S\n" +
	"\x0eAllocateChunks\x12\x1f.namenode.AllocateChunksRequest\x1a .namenode.AllocateChunksResponse\x12M\n" +
	"\fConfirmChunk\x12\x1d.namenode.ConfirmChunkRequest\x1a\x1e.namenode.ConfirmChunkResponse\x12V\n" +
	"\x0fGetFileLocation\x12 .namenode.GetFileLocationRequest\x1a!.namenode.GetFileLocationResponseB1Z/github.com/Suraj-singh04/vaultfs/proto/namenodeb\x06proto3"

var (
	file_proto_namenode_proto_rawDescOnce sync.Once
	file_proto_namenode_proto_rawDescData []byte
)

func file_proto_namenode_proto_rawDescGZIP() []byte {
	file_proto_namenode_proto_rawDescOnce.Do(func() {
		file_proto_namenode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_namenode_proto_rawDesc), len(file_proto_namenode_proto_rawDesc)))
	})
	return file_proto_namenode_proto_rawDescData
}

var file_proto_namenode_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_namenode_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),     // 0: namenode.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),    // 1: namenode.RegisterNodeResponse
	(*HeartbeatRequest)(nil),        // 2: namenode.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 3: namenode.HeartbeatResponse
	(*AllocateChunksRequest)(nil),   // 4: namenode.AllocateChunksRequest
	(*NodeList)(nil),                // 5: namenode.NodeList
	(*AllocateChunksResponse)(nil),  // 6: namenode.AllocateChunksResponse
	(*ConfirmChunkRequest)(nil),     // 7: namenode.ConfirmChunkRequest
	(*ConfirmChunkResponse)(nil),    // 8: namenode.ConfirmChunkResponse
	(*GetFileLocationRequest)(nil),  // 9: namenode.GetFileLocationRequest
	(*GetFileLocationResponse)(nil), // 10: namenode.GetFileLocationResponse
	nil,                             // 11: namenode.AllocateChunksResponse.ChunkLocationsEntry
	nil,                             // 12: namenode.GetFileLocationResponse.ChunkLocationsEntry
}
var file_proto_namenode_proto_depIdxs = []int32{
	11, // 0: namenode.AllocateChunksResponse.chunk_locations:type_name -> namenode.AllocateChunksResponse.ChunkLocationsEntry
	12, // 1: namenode.GetFileLocationResponse.chunk_locations:type_name -> namenode.GetFileLocationResponse.ChunkLocationsEntry
	5,  // 2: namenode.AllocateChunksResponse.ChunkLocationsEntry.value:type_name -> namenode.NodeList
	5,  // 3: namenode.GetFileLocationResponse.ChunkLocationsEntry.value:type_name -> namenode.NodeList
	0,  // 4: namenode.NameNode.RegisterNode:input_type -> namenode.RegisterNodeRequest
	2,  // 5: namenode.NameNode.Heartbeat:input_type -> namenode.HeartbeatRequest
	4,  // 6: namenode.NameNode.AllocateChunks:input_type -> namenode.AllocateChunksRequest
	7,  // 7: namenode.NameNode.ConfirmChunk:input_type -> namenode.ConfirmChunkRequest
	9,  // 8: namenode.NameNode.GetFileLocation:input_type -> namenode.GetFileLocationRequest
	1,  // 9: namenode.NameNode.RegisterNode:output_type -> namenode.RegisterNodeResponse
	3,  // 10: namenode.NameNode.Heartbeat:output_type -> namenode.HeartbeatResponse
	6,  // 11: namenode.NameNode.AllocateChunks:output_type -> namenode.AllocateChunksResponse
	8,  // 12: namenode.NameNode.ConfirmChunk:output_type -> namenode.ConfirmChunkResponse
	10, // 13: namenode.NameNode.GetFileLocation:output_type -> namenode.GetFileLocationResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_namenode_proto_init() }
func file_proto_namenode_proto_init() {
	if File_proto_namenode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_namenode_proto_rawDesc), len(file_proto_namenode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_namenode_proto_goTypes,
		DependencyIndexes: file_proto_namenode_proto_depIdxs,
		MessageInfos:      file_proto_namenode_proto_msgTypes,
	}.Build()
	File_proto_namenode_proto = out.File
	file_proto_namenode_proto_goTypes = nil
	file_proto_namenode_proto_depIdxs = nil
}
